/**
 * Created by xiongshengzhong on 16/8/18.
 */
'use strict';
app.controller('searchCtrl', function($scope,$rootScope) {
    $scope.theatreFlag=false;
    $scope.movieFlag=false;
    $scope.manFlag=false;
    $rootScope.searchHistoryFlag=true;
    //检查搜索历史
    $scope.checkHistory=function(){
        if(localStorage.searchHistory){
            $scope.searchHistoryData=JSON.parse(localStorage.searchHistory);
        }else{
            $scope.searchHistoryData=[];
        }
    };
    $scope.checkHistory();
    //清除历史记录
    $scope.clearSearchHistory=function(){
        $scope.searchHistoryData=[];
        localStorage.removeItem("searchHistory");
    };
    //搜索
    $scope.search=function(key){
        if(key){
            $scope.theatreFlag=true;
            $scope.movieFlag=true;
            $scope.manFlag=true;
            $rootScope.searchHistoryFlag=false;
            $scope.flag=false;
            if($scope.searchHistoryData.length>0){
                angular.forEach($scope.searchHistoryData,function(v,k){
                    if(v==key){
                        $scope.flag=true;
                    }
                });
            }
            if(!$scope.flag){
                $scope.searchHistoryData.unshift(key);
            }

            localStorage.searchHistory=JSON.stringify($scope.searchHistoryData);
        }else{
            $scope.theatreFlag=false;
            $scope.movieFlag=false;
            $scope.manFlag=false;
            $rootScope.searchHistoryFlag=true;
        }

    };
    //搜索by历史记录
    $scope.searchByHistory=function(key){
        $scope.key=key;
        $scope.theatreFlag=true;
        $scope.movieFlag=true;
        $scope.manFlag=true;
        $rootScope.searchHistoryFlag=false;
    };
});
